name: DPStamina
author: Cordori
version: '${project.version}'
main: cordori.dpstamina.DPStamina
description: '一个用于DungeonPlus的体力插件'
depend:
  - DungeonPlus
softdepend:
  - PlaceholderAPI

commands:
  dpstamina:
    permission: admin
    aliases:
      - dps